### ISSUE TITLE
hardhat-diamond-tools MVP

### ISSUE THREAD

**Issue by KyrylR** [dl-solarity/hardhat-diamond-tools#1]
### Tasks

- [ ] Runtime ABI generation to simplify diamond testing
- [ ] Rich configuration options to include/skip certain contracts & functions
- [ ] Ethers interface support
